version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/synopackage_dotnet.web/"
    schedule:
      interval: "daily"
    target-branch: "master"
  
  - package-ecosystem: "npm"
    directory: "/synopackage_dotnet.web/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "angular_update"
